joint_limits:
  ur5e_press_shoulder_pan_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
  ur5e_press_shoulder_lift_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
  ur5e_press_elbow_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 3.141592653589793
    max_velocity: 3.141592653589793
    min_position: -3.141592653589793
  ur5e_press_wrist_1_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
  ur5e_press_wrist_2_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
  ur5e_press_wrist_3_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586

  ur5e_assembly_shoulder_pan_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
  ur5e_assembly_shoulder_lift_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
  ur5e_assembly_elbow_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 3.141592653589793
    max_velocity: 3.141592653589793
    min_position: -3.141592653589793
  ur5e_assembly_wrist_1_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
  ur5e_assembly_wrist_2_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
  ur5e_assembly_wrist_3_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586

  ur3e_screw_shoulder_pan_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 54.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
  ur3e_screw_shoulder_lift_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 54.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
  ur3e_screw_elbow_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 3.141592653589793
    max_velocity: 3.141592653589793
    min_position: -3.141592653589793
  ur3e_screw_wrist_1_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 9.0
    max_position: 6.283185307179586
    max_velocity: 6.283185307179586
    min_position: -6.283185307179586
  ur3e_screw_wrist_2_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 9.0
    max_position: 6.283185307179586
    max_velocity: 6.283185307179586
    min_position: -6.283185307179586
  ur3e_screw_wrist_3_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: false
    has_velocity_limits: true
    max_effort: 9.0
    max_velocity: 6.283185307179586
